Lesson3
l1fef0r/geekshop-server pull request #2
Opened 2021-06-03 15:53 UTC by l1fef0r

2021-06-04 07:59 UTC, Vokler requested changes

2021-06-04 07:59 UTC, Vokler commented on products/models.py
> +    url = models.CharField(max_length=128, unique=True)
Если url добавляете, то тогда уже models.URLField используйте :)

2021-06-04 07:59 UTC, Vokler commented on products/views.py
> +    context['products'] = Product.objects.all()[:]
А зачем в конце добавили срез `[:]`?
Так же добавьте еще categories. И можно сразу все объявить в `context = {...}`

2021-06-06 19:14 UTC, l1fef0r commented on products/views.py
> +    context['products'] = Product.objects.all()[:]
когда выполнял, не понял в каком формате загружать в контекст.

2021-06-06 19:15 UTC, l1fef0r commented on products/models.py
> +    url = models.CharField(max_length=128, unique=True)
ок, спасибо

2021-06-07 07:32 UTC, Vokler approved these changes

2021-06-07 07:32 UTC, merged

2021-06-07 13:32 UTC, l1fef0r commented
а зачем удалили lesson3? я сделал restore, на всякий случай